export const GITHUB_FETCH_INIT = 'GITHUB_FETCH_INIT';
export const GITHUB_FETCH_SUCCESS = 'GITHUB_FETCH_SUCCESS';
export const GITHUB_FETCH_FAILED = 'GITHUB_FETCH_FAILED';
export const FILTER_REPOS = 'FILTER_REPOS';
